# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-baseline}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Reynolds"]
  s.date = %q{2010-12-17}
  s.email = %q{tdreyno@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "VERSION",
    "lib/baseline.rb",
    "lib/baseline/compass_plugin.rb",
    "lib/baseline/stylesheets/_baseline.sass",
    "lib/baseline/stylesheets/baseline/_base.sass",
    "lib/baseline/stylesheets/baseline/_form.sass",
    "lib/baseline/stylesheets/baseline/_grid.sass",
    "lib/baseline/stylesheets/baseline/_reset.sass",
    "lib/baseline/stylesheets/baseline/_table.sass",
    "lib/baseline/stylesheets/baseline/_type.sass",
    "lib/baseline/stylesheets/baseline/modules/_base.sass",
    "lib/baseline/stylesheets/baseline/modules/_form.sass",
    "lib/baseline/stylesheets/baseline/modules/_grid.sass",
    "lib/baseline/stylesheets/baseline/modules/_reset.sass",
    "lib/baseline/stylesheets/baseline/modules/_table.sass",
    "lib/baseline/stylesheets/baseline/modules/_type.sass"
  ]
  s.homepage = %q{http://github.com/tdreyno/compass-baseline}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An implementation of Baseline in Sass}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 3.0"])
      s.add_runtime_dependency(%q<compass>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 3.0"])
      s.add_dependency(%q<compass>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 3.0"])
    s.add_dependency(%q<compass>, [">= 0"])
  end
end

